export type FieldType = 'text' | 'password' | 'number' | 'date' | 'time' | 'boolean' | 'select';

export interface ResourceField {
  key: string;
  label: string;
  type: FieldType;
  required?: boolean;
  createRequired?: boolean;
  optionsEndpoint?: string;
  optionValue?: string;
  optionLabel?: string;
}

export interface ResourceConfig {
  name: string;
  endpoint: string;
  idKey: string;
  title: string;
  description: string;
  fields: ResourceField[];
  columns: string[];
}

export const RESOURCE_CONFIGS: ResourceConfig[] = [
  {
    name: 'roles',
    endpoint: '/roles',
    idKey: 'id_rol',
    title: 'Roles',
    description: 'Perfiles de acceso para usuarios del sistema.',
    columns: ['id_rol', 'nombre_rol'],
    fields: [{ key: 'nombre_rol', label: 'Nombre rol', type: 'text', required: true }],
  },
  {
    name: 'productos',
    endpoint: '/productos',
    idKey: 'id_producto',
    title: 'Productos',
    description: 'Alimentos recuperados disponibles para venta o entrega.',
    columns: ['id_producto', 'nombre', 'precio_venta', 'stock', 'estado_producto', 'fecha_vencimiento'],
    fields: [
      { key: 'nombre', label: 'Nombre', type: 'text', required: true },
      { key: 'descripcion', label: 'Descripcion', type: 'text' },
      { key: 'precio_costo', label: 'Precio costo', type: 'number' },
      { key: 'precio_venta', label: 'Precio venta', type: 'number' },
      { key: 'stock', label: 'Stock', type: 'number' },
      { key: 'estado_producto', label: 'Activo', type: 'boolean' },
      { key: 'fecha_vencimiento', label: 'Fecha vencimiento', type: 'date' },
      { key: 'fecha_preparacion', label: 'Fecha preparacion', type: 'date' },
      { key: 'hora_limite_consumo', label: 'Hora limite', type: 'time' },
      {
        key: 'id_categoria',
        label: 'Categoria',
        type: 'select',
        optionsEndpoint: '/categorias',
        optionValue: 'id_categoria',
        optionLabel: 'nombre',
      },
      {
        key: 'id_establecimiento',
        label: 'Establecimiento',
        type: 'select',
        optionsEndpoint: '/establecimientos',
        optionValue: 'id_establecimiento',
        optionLabel: 'nombre',
      },
    ],
  },
  {
    name: 'categorias',
    endpoint: '/categorias',
    idKey: 'id_categoria',
    title: 'Categorias',
    description: 'Clasificacion de alimentos recuperados.',
    columns: ['id_categoria', 'nombre', 'descripcion'],
    fields: [
      { key: 'nombre', label: 'Nombre', type: 'text', required: true },
      { key: 'descripcion', label: 'Descripcion', type: 'text' },
    ],
  },
  {
    name: 'establecimientos',
    endpoint: '/establecimientos',
    idKey: 'id_establecimiento',
    title: 'Establecimientos',
    description: 'Aliados que publican alimentos recuperables.',
    columns: ['id_establecimiento', 'nombre', 'tipo', 'telefono', 'estado', 'id_usuario'],
    fields: [
      { key: 'nombre', label: 'Nombre', type: 'text', required: true },
      { key: 'tipo', label: 'Tipo', type: 'text', required: true },
      { key: 'direccion', label: 'Direccion', type: 'text' },
      { key: 'telefono', label: 'Telefono', type: 'text' },
      { key: 'email', label: 'Email', type: 'text' },
      { key: 'descripcion', label: 'Descripcion', type: 'text' },
      { key: 'estado', label: 'Activo', type: 'boolean' },
      {
        key: 'id_usuario',
        label: 'Usuario',
        type: 'select',
        optionsEndpoint: '/usuarios',
        optionValue: 'id_usuario',
        optionLabel: 'nombre',
      },
    ],
  },
  {
    name: 'solicitudes-negocio',
    endpoint: '/solicitudes-negocio',
    idKey: 'id_solicitud',
    title: 'Solicitudes de negocio',
    description: 'Solicitudes enviadas por negocios interesados en unirse a SAVORA.',
    columns: [
      'id_solicitud',
      'nombre_propietario',
      'correo',
      'nombre_establecimiento',
      'tipo_negocio',
      'ciudad',
      'estado_solicitud',
      'fecha_solicitud',
    ],
    fields: [
      { key: 'nombre_propietario', label: 'Propietario', type: 'text', required: true },
      { key: 'correo', label: 'Correo', type: 'text', required: true },
      { key: 'celular', label: 'Celular', type: 'text' },
      { key: 'nombre_establecimiento', label: 'Establecimiento', type: 'text', required: true },
      { key: 'tipo_negocio', label: 'Tipo de negocio', type: 'text' },
      { key: 'ciudad', label: 'Ciudad', type: 'text' },
      { key: 'direccion', label: 'Direccion', type: 'text' },
      { key: 'mensaje', label: 'Mensaje', type: 'text' },
      { key: 'estado_solicitud', label: 'Estado solicitud', type: 'text' },
      { key: 'fecha_solicitud', label: 'Fecha solicitud', type: 'date' },
    ],
  },
  {
    name: 'usuarios',
    endpoint: '/usuarios',
    idKey: 'id_usuario',
    title: 'Usuarios',
    description: 'Cuentas de administradores, establecimientos, clientes y logistica.',
    columns: ['id_usuario', 'nombre', 'correo', 'telefono', 'estado', 'id_rol'],
    fields: [
      { key: 'nombre', label: 'Nombre', type: 'text', required: true },
      { key: 'correo', label: 'Correo', type: 'text', required: true },
      { key: 'contrasena', label: 'Contrasena', type: 'password', createRequired: true },
      { key: 'telefono', label: 'Telefono', type: 'text' },
      { key: 'direccion', label: 'Direccion', type: 'text' },
      { key: 'fecha_registro', label: 'Fecha registro', type: 'date' },
      { key: 'estado', label: 'Activo', type: 'boolean' },
      {
        key: 'id_rol',
        label: 'Rol',
        type: 'select',
        optionsEndpoint: '/roles',
        optionValue: 'id_rol',
        optionLabel: 'nombre_rol',
      },
    ],
  },
  {
    name: 'pedidos',
    endpoint: '/pedidos',
    idKey: 'id_pedido',
    title: 'Pedidos',
    description: 'Solicitudes de alimentos y entregas.',
    columns: ['id_pedido', 'fecha_pedido', 'estado_pedido', 'total', 'metodo_pago', 'id_usuario'],
    fields: [
      { key: 'fecha_pedido', label: 'Fecha pedido', type: 'date', required: true },
      { key: 'estado_pedido', label: 'Estado', type: 'text', required: true },
      { key: 'total', label: 'Total', type: 'number' },
      { key: 'direccion_entrega', label: 'Direccion entrega', type: 'text' },
      { key: 'metodo_pago', label: 'Metodo pago', type: 'text' },
      {
        key: 'id_usuario',
        label: 'Usuario',
        type: 'select',
        optionsEndpoint: '/usuarios',
        optionValue: 'id_usuario',
        optionLabel: 'nombre',
      },
      {
        key: 'id_establecimiento',
        label: 'Establecimiento',
        type: 'select',
        optionsEndpoint: '/establecimientos',
        optionValue: 'id_establecimiento',
        optionLabel: 'nombre',
      },
    ],
  },
  {
    name: 'entregas',
    endpoint: '/entregas',
    idKey: 'id_entrega',
    title: 'Entregas',
    description: 'Seguimiento operativo de pedidos entregados o programados.',
    columns: ['id_entrega', 'fecha_entrega', 'hora_entrega', 'estado_entrega', 'id_pedido'],
    fields: [
      { key: 'fecha_entrega', label: 'Fecha entrega', type: 'date' },
      { key: 'hora_entrega', label: 'Hora entrega', type: 'time' },
      { key: 'fecha_programada', label: 'Fecha programada', type: 'date' },
      { key: 'estado_entrega', label: 'Estado entrega', type: 'text' },
      { key: 'direccion_entrega', label: 'Direccion entrega', type: 'text' },
      { key: 'observaciones', label: 'Observaciones', type: 'text' },
      {
        key: 'id_pedido',
        label: 'Pedido',
        type: 'select',
        optionsEndpoint: '/pedidos',
        optionValue: 'id_pedido',
        optionLabel: 'estado_pedido',
      },
    ],
  },
  {
    name: 'adultos-mayores',
    endpoint: '/adultos-mayores',
    idKey: 'id_adulto_mayor',
    title: 'Adultos mayores',
    description: 'Beneficiarios con datos de contacto y observaciones medicas.',
    columns: ['id_adulto_mayor', 'nombre', 'documento', 'telefono', 'id_usuario'],
    fields: [
      { key: 'nombre', label: 'Nombre', type: 'text', required: true },
      { key: 'documento', label: 'Documento', type: 'text' },
      { key: 'fecha_nacimiento', label: 'Fecha nacimiento', type: 'date' },
      { key: 'telefono', label: 'Telefono', type: 'text' },
      { key: 'direccion', label: 'Direccion', type: 'text' },
      { key: 'observaciones_medicas', label: 'Observaciones medicas', type: 'text' },
      {
        key: 'id_usuario',
        label: 'Usuario',
        type: 'select',
        optionsEndpoint: '/usuarios',
        optionValue: 'id_usuario',
        optionLabel: 'nombre',
      },
    ],
  },
  {
    name: 'proveedores',
    endpoint: '/proveedores',
    idKey: 'id_proveedor',
    title: 'Proveedores',
    description: 'Empresas o contactos que abastecen productos.',
    columns: ['id_proveedor', 'nombre', 'contacto', 'telefono', 'ciudad'],
    fields: [
      { key: 'nombre', label: 'Nombre', type: 'text', required: true },
      { key: 'contacto', label: 'Contacto', type: 'text' },
      { key: 'telefono', label: 'Telefono', type: 'text' },
      { key: 'direccion', label: 'Direccion', type: 'text' },
      { key: 'email', label: 'Email', type: 'text' },
      { key: 'pagina_web', label: 'Pagina web', type: 'text' },
      { key: 'ciudad', label: 'Ciudad', type: 'text' },
    ],
  },
  {
    name: 'productos-proveedores',
    endpoint: '/productos-proveedores',
    idKey: 'id_producto_proveedor',
    title: 'Productos proveedores',
    description: 'Relacion de compras entre productos y proveedores.',
    columns: ['id_producto_proveedor', 'precio_compra', 'fecha_compra', 'id_producto', 'id_proveedor'],
    fields: [
      { key: 'precio_compra', label: 'Precio compra', type: 'number' },
      { key: 'fecha_compra', label: 'Fecha compra', type: 'date' },
      {
        key: 'id_producto',
        label: 'Producto',
        type: 'select',
        optionsEndpoint: '/productos',
        optionValue: 'id_producto',
        optionLabel: 'nombre',
      },
      {
        key: 'id_proveedor',
        label: 'Proveedor',
        type: 'select',
        optionsEndpoint: '/proveedores',
        optionValue: 'id_proveedor',
        optionLabel: 'nombre',
      },
    ],
  },
  {
    name: 'movimientos',
    endpoint: '/movimientos',
    idKey: 'id_movimiento',
    title: 'Movimientos',
    description: 'Entradas, salidas y ajustes de inventario.',
    columns: ['id_movimiento', 'tipo_movimiento', 'motivo', 'cantidad', 'fecha', 'id_producto'],
    fields: [
      { key: 'tipo_movimiento', label: 'Tipo movimiento', type: 'text', required: true },
      { key: 'motivo', label: 'Motivo', type: 'text', required: true },
      { key: 'cantidad', label: 'Cantidad', type: 'number', required: true },
      { key: 'fecha', label: 'Fecha', type: 'date', required: true },
      { key: 'descripcion', label: 'Descripcion', type: 'text' },
      {
        key: 'id_producto',
        label: 'Producto',
        type: 'select',
        optionsEndpoint: '/productos',
        optionValue: 'id_producto',
        optionLabel: 'nombre',
      },
      {
        key: 'id_usuario',
        label: 'Usuario',
        type: 'select',
        optionsEndpoint: '/usuarios',
        optionValue: 'id_usuario',
        optionLabel: 'nombre',
      },
    ],
  },
  {
    name: 'detalle-pedido',
    endpoint: '/detalle-pedido',
    idKey: 'id_detalle_pedido',
    title: 'Detalle pedido',
    description: 'Productos y cantidades asociados a cada pedido.',
    columns: ['id_detalle_pedido', 'id_pedido', 'id_producto', 'cantidad', 'subtotal'],
    fields: [
      {
        key: 'id_pedido',
        label: 'Pedido',
        type: 'select',
        optionsEndpoint: '/pedidos',
        optionValue: 'id_pedido',
        optionLabel: 'estado_pedido',
      },
      {
        key: 'id_producto',
        label: 'Producto',
        type: 'select',
        optionsEndpoint: '/productos',
        optionValue: 'id_producto',
        optionLabel: 'nombre',
      },
      { key: 'cantidad', label: 'Cantidad', type: 'number', required: true },
      { key: 'precio_unitario', label: 'Precio unitario', type: 'number', required: true },
      { key: 'subtotal', label: 'Subtotal', type: 'number', required: true },
    ],
  },
  {
    name: 'preferencias-alimentarias',
    endpoint: '/preferencias-alimentarias',
    idKey: 'id_preferencia_alimentaria',
    title: 'Preferencias alimentarias',
    description: 'Restricciones, alergias y horarios de entrega.',
    columns: ['id_preferencia_alimentaria', 'restricciones', 'alergias', 'frecuencia', 'id_adulto_mayor'],
    fields: [
      { key: 'restricciones', label: 'Restricciones', type: 'text' },
      { key: 'alergias', label: 'Alergias', type: 'text' },
      { key: 'observaciones', label: 'Observaciones', type: 'text' },
      { key: 'horario_entrega', label: 'Horario entrega', type: 'time' },
      { key: 'frecuencia', label: 'Frecuencia', type: 'text' },
      {
        key: 'id_adulto_mayor',
        label: 'Adulto mayor',
        type: 'select',
        optionsEndpoint: '/adultos-mayores',
        optionValue: 'id_adulto_mayor',
        optionLabel: 'nombre',
      },
    ],
  },
  {
    name: 'programacion-entregas',
    endpoint: '/programacion-entregas',
    idKey: 'id_programacion_entregas',
    title: 'Programacion entregas',
    description: 'Rutinas de entrega recurrente para beneficiarios.',
    columns: ['id_programacion_entregas', 'frecuencia', 'horario', 'estado', 'id_adulto_mayor'],
    fields: [
      { key: 'frecuencia', label: 'Frecuencia', type: 'text' },
      { key: 'horario', label: 'Horario', type: 'time' },
      { key: 'estado', label: 'Activo', type: 'boolean' },
      { key: 'fecha_inicio', label: 'Fecha inicio', type: 'date' },
      {
        key: 'id_adulto_mayor',
        label: 'Adulto mayor',
        type: 'select',
        optionsEndpoint: '/adultos-mayores',
        optionValue: 'id_adulto_mayor',
        optionLabel: 'nombre',
      },
    ],
  },
  {
    name: 'promociones',
    endpoint: '/promociones',
    idKey: 'id_promocion',
    title: 'Promociones',
    description: 'Descuentos aplicados a productos recuperados.',
    columns: ['id_promocion', 'porcentaje_descuento', 'fecha_inicio', 'fecha_fin', 'estado', 'id_producto'],
    fields: [
      { key: 'porcentaje_descuento', label: 'Porcentaje descuento', type: 'number' },
      { key: 'fecha_inicio', label: 'Fecha inicio', type: 'date' },
      { key: 'fecha_fin', label: 'Fecha fin', type: 'date' },
      { key: 'estado', label: 'Activo', type: 'boolean' },
      { key: 'tipo_promocion', label: 'Tipo promocion', type: 'text' },
      {
        key: 'id_producto',
        label: 'Producto',
        type: 'select',
        optionsEndpoint: '/productos',
        optionValue: 'id_producto',
        optionLabel: 'nombre',
      },
    ],
  },
  {
    name: 'notificaciones',
    endpoint: '/notificaciones',
    idKey: 'id_notificacion',
    title: 'Notificaciones',
    description: 'Mensajes para usuarios y seguimiento del sistema.',
    columns: ['id_notificacion', 'titulo', 'mensaje', 'estado', 'id_usuario'],
    fields: [
      { key: 'titulo', label: 'Titulo', type: 'text' },
      { key: 'mensaje', label: 'Mensaje', type: 'text', required: true },
      { key: 'estado', label: 'Estado', type: 'text' },
      {
        key: 'id_usuario',
        label: 'Usuario',
        type: 'select',
        optionsEndpoint: '/usuarios',
        optionValue: 'id_usuario',
        optionLabel: 'nombre',
      },
    ],
  },
];
